<?php
namespace drought\controllers\api;

use common\controllers\ApiController;
use common\models\DmPhuong;
use drought\models\Gallery;
use drought\models\HcTinh;
use drought\models\HcVung;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use ttungbmt\db\Query;
use yii\db\Expression;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;

class DmController extends ApiController
{
    public function beforeAction($action)
    {
        if(in_array($action->id, ['quan'])){
            $this->attachBehaviors([
                'authenticator' => [
                    'class' => CompositeAuth::className(),
                    'authMethods' => [
                        HttpBasicAuth::className(),
                        HttpBearerAuth::className(),
                        QueryParamAuth::className(),
                    ],
                ]
            ]);
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionYear(){
        $type = request('type');
        $years = (new \ttungbmt\db\Query())->select(new \yii\db\Expression('DISTINCT year'))->from('gallery')
            ->andWhere('year IS NOT NULL')
            ->andFilterWhere(['type' => $type])
            ->orderBy('year DESC')->all();
        $dm_year = \Illuminate\Support\Arr::pluck($years, 'year', 'year');
        return $dm_year;
    }

    public function actionImgByYear($year){

    }


    public function actionTinh()
    {
        $value = app('request')->post('value');
        $mavung = data_get(app('request')->post('depdrop_parents'), '0');

        $list = collect(data_get(HcVung::find()->with('tinhs')->where(['mavung' => $mavung])->one(), 'tinhs'))->map(function ($item){
            return ['id' => $item->gid, 'name' => $item->tentinh];
        });


        return [
            'output' => $list, 'selected'=> $value
        ];
    }

    public function actionVung()
    {
        $query = HcVung::find()->select('mavung, tenvung');
        return $query->pluck('tenvung', 'mavung');
    }

    public function actionDmFolderAll(){
//        SELECT folder, year FROM gallery GROUP BY 1, 2 ORDER BY 2 DESC
        $data = collect((new Query)->select('folder, year')
            ->from('gallery')
            ->orderBy(new Expression('2 DESC'))
            ->groupBy(new Expression('1, 2'))->all());

        $dm_folder = array_merge(api('dm_folder'), ['cdi' => 'CDI']);

        return $data->groupBy('folder')->map(function ($i, $k) use($dm_folder){
            return [
                'label' => data_get($dm_folder, $k),
                'value' => $k,
                'years' => $i->pluck('year')
            ];
        })->values();
    }

    public function actionResults($year, $folder)
    {
        $data = Gallery::find()->select('code, id, date, metadata, symbology')
            ->andWhere(['year' => $year, 'folder' => $folder])
            ->asArray()->all();

        $data = collect($data)->map(function ($i){
            $layers = (string)Str::of($i['code'])->prepend('drought:m_');
            $metadata = json_decode($i['metadata'], true) ?? [];

            return array_merge($i, [
                'layers' => $layers,
                'symbology' => json_decode($i['symbology']),
                'bounds' => collect([
                    data_get($metadata, 'cornerCoordinates.lowerLeft'),
                    data_get($metadata, 'cornerCoordinates.upperRight')
                ])->filter()->map(function ($i){
                    return array_reverse($i);
                })
            ]);
        })->all();

        $vung = collect(HcVung::find()->with('tinhs')->select('id, mavung, tenvung')->all())->map(function ($i){
            $cql = Str::of(implode(',', Arr::pluck($i->tinhs, 'gid')))->prepend('gid in (')->append(')');
            return [
                'value' => $i->id,
                'label' => $i->tenvung,
                'cql' => (string)$cql
            ];
        });

        return [
            'data' => [
                'vungs' => $vung->all(),
                'results' => $this->parseCat($data, 'id', 'code', ['layers', 'date', 'bounds', 'symbology'])
            ]
        ];
    }


    public function parseCat($data, $value, $label, $only = []){
        return collect($data)->map(function ($i, $k) use($value, $label, $only){
            $data = collect($i);

            if($only) $data = $data->only($only);

            return $data->merge([
                'label' => $i[$label],
                'value' => $i[$value],
            ])->all();
        })->values()->all();
    }
}